### ISSUE TITLE
Found a new way to do the same thing

### ISSUE THREAD

**Issue by HypsyNZ** [HyperSine/Windows10-CustomKernelSigners#9]
https://github.com/HypsyNZ/DSEDodge-Signed-Kernel-Driver

**Comment by Puppeteer-rg** [comment]
I did all the steps but windows crashes on boot.

**Comment by HypsyNZ** [comment]
> I did all the steps but windows crashes on boot.

Yeah this method will only work on some motherboards, if you updated your bios it may already be patched try an earlier version

**Comment by HypsyNZ** [comment]
you did something wrong for sure if your computer is crashing on boot.

**Comment by Puppeteer-rg** [comment]
I added the cer files in my secure boot db, replaced my PK key, I cleared the keys and it still didn't work. When you try to run your driver does it give you the windows signature error?

**Comment by HypsyNZ** [comment]
You aren't following the instructions correctly.

**Comment by Puppeteer-rg** [comment]
I did all steps, I created the certificates (I did with changing the names and without), I put the cer files in a usb, added the cer files to the db of secure boot, Added the certificate to the Trusted Root Certification Authorities, Signed both .cat and .sys file. Installed my driver with an .inf file.

Operation was completed.

Is this even used for Kernel Drivers? Like if I do "sc start %serviceName%"  it'll return that windows cannot verify the signature.

**Comment by HypsyNZ** [comment]
> Is this even used for Kernel Drivers? Like if I do "sc start %serviceName%" it'll return that windows cannot verify the signature.

Then you did it wrong.

**Comment by Puppeteer-rg** [comment]
Downgraded to windows 21h2, did all the steps and yet windows still says it's unable to verify the signature.

**Comment by HypsyNZ** [comment]
Then you did something wrong.

**Comment by HypsyNZ** [comment]
Unfortunately I can't help you with the problem you are experiencing, maybe you should start again.

**Comment by Puppeteer-rg** [comment]
I am just asking if how it works. Can you run the service by doing `sc start serviceName` or by making it run on boot then it works?

**Comment by HypsyNZ** [comment]
What someone else can do and what you can do are obviously different things.

**Comment by Puppeteer-rg** [comment]
I've tried doing everything the same. Just please tell me how do you run the driver so that I know how it works.

**Comment by louga31** [comment]
@Puppeteer-rg you should definitely learn how to make a driver and how it works, before trying to find a bypass to make it run with DSE

**Comment by Puppeteer-rg** [comment]
I'm using the kmdfdriver that's given. Made the certs and added it into the secure boot database then installed it. Device manager shows the driver but it doesn't run.

**Comment by HypsyNZ** [comment]
I can't help you, Microsoft will patch this if I give you more help.

**Comment by xperia64** [comment]
Hi, just curious, why is this repo unavailable now (and all forks with it)?

**Comment by HypsyNZ** [comment]
This content is no longer available, sorry.

**Comment by xperia64** [comment]
I'm afraid I don't see why, as the steps detailed are just the Windows equivalent of the process you would go through to secure-boot sign kernel drivers on Linux with extra signatures in addition to the primary platform ones. I wouldn't consider it a flaw either, more Microsoft actually respecting the user's secure boot configuration and actually giving them power for once (if it is a flaw, well, it's already public so if you're worried about it getting patched, it's probably too late for that).

I have not yet attempted the process, but I see nothing wrong with the instructions themselves to warrant their removal.

https://pastebin.com/U2mNQHVr

**Comment by HypsyNZ** [comment]
You couldn't even get it to work you can't patch it who are you kidding.
